name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: labs/40-containerized-node-app/app
        run: npm ci

      - name: Run tests if present
        working-directory: labs/40-containerized-node-app/app
        run: npm test --if-present

      - name: Build Docker image
        run: docker build -t quote-app -f labs/40-containerized-node-app/docker/Dockerfile labs/40-containerized-node-app

      - name: Installer jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run container
        run: |
          docker run -d --name quote-app -p 3000:3000 quote-app
          for i in $(seq 1 30); do
            response=$(curl -fsS http://localhost:3000/health || true)

            if echo "$response" | jq -e '.status == "healthy"' > /dev/null 2>&1; then
              echo "La vérification de l'état a réussi"
              exit 0
            fi
            sleep 5
          done
          echo "La vérification de l'état a échoué"
          docker logs quote-app || true
          exit 1

      - name: Stop container
        if: always()
        run: |
          docker rm -f quote-app || true